export const Films = [
  {
    id: 1,
    name: "Better Call Saul",
    cost: 50.0,
    title: "The show premiered on AMC on February 8, 2015 in American",
    img: "assets/images/BCS.jpg",
    info: "Better Call Saul is an American crime and legal drama television series created by Vince Gilligan and Peter Gould. Part of the Breaking Bad franchise, it is a spin-off, prequel and sequel to Gilligan's previous series, Breaking Bad. Set primarily in the early-mid 2000s in Albuquerque, New Mexico, the series develops Jimmy McGill (Bob Odenkirk), an earnest lawyer and former con artist, into an egocentric criminal defense attorney known as Saul Goodman. Also shown is the moral decline of former police officer Mike Ehrmantraut (Jonathan Banks), who becomes a violent fixer for drug traffickers to support his granddaughter and her widowed mother. The show premiered on AMC on February 8, 2015, and concluded on August 15, 2022, after six seasons consisting of 63 episodes.",
    clip: "https://www.youtube.com/embed/Qz3u06eXf0E",
  },
  {
    id: 2,
    name: "Breaking Bad",
    cost: 50.0,
    title: "The show aired on AMC from January 20, 2008 in American",
    img: "assets/images/BK.jpg",
    info: "Breaking Bad is an American crime drama television series created and produced by Vince Gilligan. Set and filmed in Albuquerque, New Mexico, the series follows Walter White (Bryan Cranston), an underpaid, overqualified, and dispirited high-school chemistry teacher who is struggling with a recent diagnosis of stage-three lung cancer. White turns to a life of crime and partners with a former student, Jesse Pinkman (Aaron Paul), to produce and distribute crystal meth to secure his family's financial future before he dies, while navigating the dangers of the criminal underworld. The show aired on AMC from January 20, 2008, to September 29, 2013, consisting of five seasons for a total of 62 episodes.",
    clip: "https://www.youtube.com/embed/ceqOTZnhgY8",
  },
  {
    id: 3,
    cost: 50.0,
    name: "Bates Motel",
    title: "The film premiered on July 5, 1987 in American",
    img: "assets/images/BM.jpg",
    info: "The series begins in Arizona with the death of Norma's husband, after which Norma purchases the Seafairer motel located in a coastal Oregon town so that she and Norman can start a new life.[4][7][8] Subsequent seasons follow Norman as his mental illness becomes dangerous, and Norma as she struggles to protect her son, and those around him, from himself. The series was filmed outside Vancouver in Aldergrove, British Columbia, along with other locations within the Fraser Valley of British Columbia.",
    clip: "https://www.youtube.com/embed/7lCWKKNGiKs",
  },
  {
    id: 4,
    cost: 50.0,
    name: "Don't Breathe 2",
    title: "The film premiered on 2018 in American",
    img: "assets/images/DB.jpg",
    info: "Don't Breathe is a 2016 American horror-thriller film produced and directed by Fede Álvarez, co-produced by Sam Raimi and Robert Tapert, and co-written by Álvarez and Rodo Sayagues. The film stars Jane Levy, Dylan Minnette, Daniel Zovatto and Stephen Lang, and focuses on three friends who get trapped inside a blind man's house while breaking into it. The film was produced by Ghost House Pictures and Good Universe and distributed by Sony Pictures Releasing.",
    clip: "https://www.youtube.com/embed/gRbG2tjHYCA",
  },
  {
    id: 5,
    cost: 50.0,
    name: "Game of Throne",
    title: "The film premiered on HBO on April 17, 2011 in American",
    img: "assets/images/GOT.jpg",
    info: "Game of Thrones is an American fantasy drama television series created by David Benioff and D. B. Weiss for HBO. It is an adaptation of A Song of Ice and Fire, a series of fantasy novels by George R. R. Martin, the first of which is A Game of Thrones. The show was shot in the United Kingdom, Canada, Croatia, Iceland, Malta, Morocco, and Spain. It premiered on HBO in the United States on April 17, 2011, and concluded on May 19, 2019, with 73 episodes broadcast over eight seasons.",
    clip: "https://www.youtube.com/embed/KPLWWIOCOOQ",
  },
  {
    id: 6,
    cost: 50.0,
    name: "House of Dragon",
    title: "The series premiered on August 21, 2022 in American",
    img: "assets/images/HOD.jpg",
    info: "House of the Dragon is an American fantasy drama television series. A prequel to Game of Thrones (2011–2019), it is the second show in the franchise, created by George R. R. Martin and Ryan Condal for HBO. Both series are based on the A Song of Ice and Fire novels by Martin. Condal and Miguel Sapochnik are the showrunners. Based on parts of the novel Fire & Blood, the series is set about 200 years before the events of Game of Thrones, and 172 years before the birth of Daenerys Targaryen. It portrays the beginning of the end of House Targaryen, the events leading up to and covering the Targaryen war of succession, known as the Dance of the Dragons.",
    clip: "https://www.youtube.com/embed/DotnJ7tTA34",
  },
  {
    id: 7,
    cost: 50.0,
    name: "Stranger Things",
    title: "The show premiered on October, 2017 in American",
    img: "assets/images/ST.jpg",
    info: "Stranger Things is an American science fiction horror drama television series created by the Duffer Brothers, who also serve as showrunners and are executive producers along with Shawn Levy and Dan Cohen. Produced by Monkey Massacre Productions and Levy's 21 Laps Entertainment, the first season was released on Netflix on July 15, 2016. Its second, third, and fourth seasons followed in October 2017, July 2019, and May and July 2022, respectively. In February 2022, the series was renewed for a fifth and final season.",
    clip: "https://www.youtube.com/embed/b9EkMc79ZSU",
  },
  {
    id: 8,
    cost: 50.0,
    name: "The Boys",
    title: "The show premiered on July 26, 2019 in American",
    img: "assets/images/TB.jpg",
    info: "The Boys is an American superhero television series developed by Eric Kripke for Amazon Prime Video. Based on the comic book of the same name by Garth Ennis and Darick Robertson, it follows the eponymous team of vigilantes as they combat superpowered individuals who abuse their abilities. The series features an ensemble cast that includes Karl Urban, Jack Quaid, Antony Starr, Erin Moriarty, Dominique McElligott, Jessie T. Usher, Chace Crawford, Laz Alonso, Tomer Capone, Karen Fukuhara, and Nathan Mitchell.",
    clip: "https://www.youtube.com/embed/tcrNsIaQkb4",
  },
  {
    id: 9,
    cost: 50.0,
    name: "The Walking Dead",
    title: "The series premiered on October 31, 2010 in American",
    img: "assets/images/TWD.jpg",
    info: "The Walking Dead is an American post-apocalyptic horror television series based on the comic book series of the same name by Robert Kirkman, Tony Moore, and Charlie Adlard—together forming the core of The Walking Dead franchise. The series features a large ensemble cast as survivors of a zombie apocalypse trying to stay alive under near-constant threat of attacks from zombies known as walkers (among other nicknames). With the collapse of modern civilization, these survivors must confront other human survivors who have formed groups and communities with their own sets of laws and morals, sometimes leading to open, hostile conflict between them.",
    clip: "https://www.youtube.com/embed/oXWYauB7_AU",
  },
];
